### ISSUE TITLE
Nasadenie aplikácie

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/mdns#14]
Vyriešiť nasadenie na [DigitalOcean](https://www.digitalocean.com/) a vytvorenie online prístupu. Deploy scripts ideálne napísať cez [Fabric](https://www.fabfile.org/).

Aplikovať tradičný Python produkčný setup: 

- [virtualenv](https://virtualenv.pypa.io/en/latest/) + [Pipenv](https://github.com/pypa/pipenv): Python prostredie
- [Gunicorn](https://gunicorn.org/): Aplikačný server
- [Supervisor](http://supervisord.org/): Sledovanie aplikačného procesu
- [Nginx](https://nginx.org/en/): Reverse proxy

Najjednoduchšia možnosť je vytvorenie [Ubuntu 18.04 LTS](https://www.ubuntu.com/download/server) dropletu a separátnej [PostgreSQL](https://www.postgresql.org/) inštancie (DigitaOcean začal podporovať dedikované databázové inštancie a chcem to vyskúšať, nechcem tiež zbytočne zaťažovať aplikačný droplet, pretože budem rád ak ten chudák bude vôbec bežať).

**TODO**

- [x] Vytvorenie dropletu
- [x] Presmerovanie `mdns.jakubdubec.me` domény
- [x] Napísanie deploy scriptov
- [x] Unit deamon script pre Gunicorn
- [x] Nastavenie SSH kľúčov (kvôli GitHub)
- [x] Nastavenie sytémového Python interpréta
- [x] Nginx
- [x] Lets encrypt
